### ISSUE TITLE
GoalGAN-DDPG

### ISSUE THREAD

**Issue by 759223466** [SanteriHei/GoalGAN-DDPG#1]
May I ask which academic paper this code corresponds to?

**Comment by SanteriHei** [comment]
Hi, 
This work is an adaptation of the paper "Florensa, C., Held, D., Geng, X. &amp; Abbeel, P.. (2018). Automatic Goal Generation for Reinforcement Learning Agents. <i>Proceedings of the 35th International Conference on Machine Learning</i>, in <i>Proceedings of Machine Learning Research</i> 80:1515-1528 Available from https://proceedings.mlr.press/v80/florensa18a.html."
Compared to the original work, this code utilizes a DDPG instead of TRPO.  I have added the citation to the original work to the README.
